-- -----------------------------------------------------
-- Table `manager-tran-school`.`USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `USUARIO` ;

CREATE  TABLE IF NOT EXISTS USUARIO(
  `ID_USUARIO` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE ,
  `TX_LOGIN` VARCHAR(12) NOT NULL UNIQUE,
  `TX_SENHA` VARCHAR(12) NOT NULL,      
  TIPO_USUARIO INTEGER NOT NULL,
  TX_NOME VARCHAR(45) NOT NULL);

-- -----------------------------------------------------
-- Table `manager-tran-school`.`ESTADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ESTADO` ;

CREATE  TABLE IF NOT EXISTS ESTADO(
  `ID_ESTADO` CHAR(2) NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE ,
  `TX_DESCRICAO` VARCHAR(45) NOT NULL UNIQUE);
INSERT INTO ESTADO (ID_ESTADO, TX_DESCRICAO)
VALUES ('BA', 'BAHIA')
-- -----------------------------------------------------
-- Table `manager-tran-school`.`CIDADE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CIDADE` ;

CREATE  TABLE IF NOT EXISTS CIDADE(
  `ID_CIDADE` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE ,
  `TX_DESCRICAO` VARCHAR(45) NOT NULL,
  `ESTADO_ID` CHAR(2) NOT NULL REFERENCES ESTADO ( ID_ESTADO ));

INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID)
VALUES (1, 'Salvador', 'BA')

-- -----------------------------------------------------
-- Table `manager-tran-school`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CLIENTE` ;

CREATE  TABLE IF NOT EXISTS CLIENTE(
  `ID_CLIENTE` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE ,
  `TX_NOME` VARCHAR(80) NOT NULL,
  `TX_ENDERECO` VARCHAR(80) NOT NULL,      
  CIDADE_ID INTEGER NOT NULL REFERENCES CIDADE ( ID_CIDADE ),
  CEP CHAR(12) NULL,
  TX_EMAIL VARCHAR(45) NULL,
  CPF VARCHAR(11) NOT NULL UNIQUE,
  TX_BAIRRO VARCHAR(45) NOT NULL,
  NR_TELEFONE_PRIMARIO VARCHAR(15) NULL,
  NR_TELEFONE_SECUNDARIO VARCHAR(15) NULL);
        
-- -----------------------------------------------------
-- Table `manager-tran-school`.`LOCALIDADE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LOCALIDADE` ;

CREATE  TABLE IF NOT EXISTS LOCALIDADE(
  `ID_LOCALIDADE` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE ,
  `NR_LATITUDE` DOUBLE NOT NULL,
  `NR_LONGITUDE` DOUBLE NOT NULL,
  `TX_DESCRICAO` VARCHAR(45) NOT NULL);
  
-- -----------------------------------------------------
-- Table `manager-tran-school`.`PAGAMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PAGAMENTO` ;

CREATE  TABLE IF NOT EXISTS PAGAMENTO(
  `ID_PAGAMENTO` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE ,
  `CLIENTE_ID` INTEGER NOT NULL REFERENCES CLIENTE ( ID_CLIENTE ),
  `TIPO_PAGAMENTO` INTEGER NOT NULL,
  `VALOR` DECIMAL(7,2) NOT NULL,
  `DT_VENCIMENTO` DATETIME NOT NULL);    
       
-- -----------------------------------------------------
-- Table `manager-tran-school`.`PAGAMENTO_REALIZADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PAGAMENTO_REALIZADO` ;

CREATE  TABLE IF NOT EXISTS PAGAMENTO_REALIZADO(
  `ID_PAGAMENTO_REALIZADO` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE ,
  `PAGAMENTO_ID` INTEGER NOT NULL REFERENCES PAGAMENTO ( ID_PAGAMENTO ),
  `DT_PAGAMENTO` DATETIME NOT NULL,
  `MES_ANO_REFERENTE` DATE NOT NULL);    
  
-- -----------------------------------------------------
-- Table `manager-tran-school`.`ROTA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ROTA` ;

CREATE  TABLE IF NOT EXISTS ROTA(
  `ID_ROTA` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE ,
  `TX_DESCRICAO` VARCHAR(45) NOT NULL ,
  `LOCAL_PARTIDA_ID` INTEGER NOT NULL REFERENCES LOCALIDADE ( ID_LOCALIDADE ));       
      
-- -----------------------------------------------------
-- Table `manager-tran-school`.`ROTA_LOCALIDADE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ROTA_LOCALIDADE` ;

CREATE TABLE IF NOT EXISTS `ROTA_LOCALIDADE`( 
  `ROTA_ID` INTEGER NOT NULL REFERENCES ROTA ( ID_ROTA ),
  `LOCALIDADE_ID` INTEGER NOT NULL REFERENCES LOCALIDADE ( ID_LOCALIDADE ),
  PRIMARY KEY ( ROTA_ID, LOCALIDADE_ID ));

-- -----------------------------------------------------
-- Table `manager-tran-school`.`CLIENTE_LOCALIDADE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CLIENTE_LOCALIDADE` ;

CREATE TABLE IF NOT EXISTS `CLIENTE_LOCALIDADE`(
  `CLIENTE_ID` INTEGER NOT NULL REFERENCES CLIENTE ( ID_CLIENTE ) ,
  `LOCALIDADE_ID` INTEGER NOT NULL REFERENCES LOCALIDADE ( ID_LOCALIDADE ),
  PRIMARY KEY (`CLIENTE_ID`, `LOCALIDADE_ID`));
    
-- -----------------------------------------------------
-- Table `manager-tran-school`.`ROTA_HISTORICO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ROTA_HISTORICO`;

CREATE  TABLE IF NOT EXISTS `ROTA_HISTORICO`(
  `ID_ROTA_HISTORICO` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE ,
  `ROTA_ID` INTEGER NOT NULL REFERENCES ROTA ( ID_ROTA ) ,
  `DT_ROTA` DATETIME NOT NULL ,
  `DURACAO` TIME NULL ,
  `USUARIO_ID` INTEGER NOT NULL);
    
-- -----------------------------------------------------
-- Table `manager-tran-school`.`CLIENTE_ROTA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CLIENTE_ROTA` ;

CREATE  TABLE IF NOT EXISTS `CLIENTE_ROTA`(
  `CLIENTE_ID` INTEGER NOT NULL REFERENCES CLIENTE ( ID_CLIENTE ) ,
  `ROTA_ID` INTEGER NOT NULL REFERENCES ROTA ( ID_ROTA ) ,
  PRIMARY KEY (`CLIENTE_ID`, `ROTA_ID`));    
            
-- -----------------------------------------------------
-- Massa de dados - Unidades federativas do Brasil
-- -----------------------------------------------------
INSERT INTO ESTADO (ID_ESTADO, TX_DESCRICAO) VALUES ('AC', 'Acre');
INSERT INTO ESTADO (ID_ESTADO, TX_DESCRICAO) VALUES ('AL', 'Alagoas');
INSERT INTO ESTADO (ID_ESTADO, TX_DESCRICAO) VALUES ('AP', 'Amapá');
INSERT INTO ESTADO (ID_ESTADO, TX_DESCRICAO) VALUES ('AM', 'Amazonas');
INSERT INTO ESTADO (ID_ESTADO, TX_DESCRICAO) VALUES ('BA', 'Bahia');
INSERT INTO ESTADO (ID_ESTADO, TX_DESCRICAO) VALUES ('CE', 'Ceará');
INSERT INTO ESTADO (ID_ESTADO, TX_DESCRICAO) VALUES ('DF', 'Distrito Federal');
INSERT INTO ESTADO (ID_ESTADO, TX_DESCRICAO) VALUES ('ES', 'Espírito Santo');
INSERT INTO ESTADO (ID_ESTADO, TX_DESCRICAO) VALUES ('GO', 'Goiás');
INSERT INTO ESTADO (ID_ESTADO, TX_DESCRICAO) VALUES ('MA', 'Maranhão');
INSERT INTO ESTADO (ID_ESTADO, TX_DESCRICAO) VALUES ('MT', 'Mato Grosso');
INSERT INTO ESTADO (ID_ESTADO, TX_DESCRICAO) VALUES ('MS', 'Mato Grosso do Sul');
INSERT INTO ESTADO (ID_ESTADO, TX_DESCRICAO) VALUES ('MG', 'Minas Gerais');
INSERT INTO ESTADO (ID_ESTADO, TX_DESCRICAO) VALUES ('PE', 'Pernambuco');
INSERT INTO ESTADO (ID_ESTADO, TX_DESCRICAO) VALUES ('PI', 'Piauí');
INSERT INTO ESTADO (ID_ESTADO, TX_DESCRICAO) VALUES ('RJ', 'Rio de Janeiro');
INSERT INTO ESTADO (ID_ESTADO, TX_DESCRICAO) VALUES ('RN', 'Rio Grande do Norte');
INSERT INTO ESTADO (ID_ESTADO, TX_DESCRICAO) VALUES ('RS', 'Rio Grande do Sul');
INSERT INTO ESTADO (ID_ESTADO, TX_DESCRICAO) VALUES ('RO', 'Rondônia');
INSERT INTO ESTADO (ID_ESTADO, TX_DESCRICAO) VALUES ('RR', 'Roraima');
INSERT INTO ESTADO (ID_ESTADO, TX_DESCRICAO) VALUES ('SC', 'Santa Catarina');
INSERT INTO ESTADO (ID_ESTADO, TX_DESCRICAO) VALUES ('PR', 'Paraná');
INSERT INTO ESTADO (ID_ESTADO, TX_DESCRICAO) VALUES ('PB', 'Paraíba');
INSERT INTO ESTADO (ID_ESTADO, TX_DESCRICAO) VALUES ('PA', 'Pará');
INSERT INTO ESTADO (ID_ESTADO, TX_DESCRICAO) VALUES ('SP', 'São Paulo');
INSERT INTO ESTADO (ID_ESTADO, TX_DESCRICAO) VALUES ('SE', 'Sergipe');
INSERT INTO ESTADO (ID_ESTADO, TX_DESCRICAO) VALUES ('TO', 'Tocantins');            

-- -----------------------------------------------------
-- Massa de dados - Municípios do Estado da Bahia-Brasil
-- -----------------------------------------------------
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290010, 'ABAIRA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290020, 'ABARE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290030, 'ACAJUTIBA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290035, 'ADUSTINA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290040, 'AGUA FRIA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290050, 'ERICO CARDOSO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290060, 'AIQUARA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290070, 'ALAGOINHAS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290080, 'ALCOBACA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290090, 'ALMADINA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290100, 'AMARGOSA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290110, 'AMELIA RODRIGUES', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290115, 'AMERICA DOURADA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290120, 'ANAGE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290130, 'ANDARAI', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290135, 'ANDORINHA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290140, 'ANGICAL', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290150, 'ANGUERA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290160, 'ANTAS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290170, 'ANTONIO CARDOSO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290180, 'ANTONIO GONCALVES', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290190, 'APORA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290195, 'APUAREMA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290200, 'ARACATU', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290205, 'ARACAS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290210, 'ARACI', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290220, 'ARAMARI', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290225, 'ARATACA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290230, 'ARATUIPE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290240, 'AURELINO LEAL', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290250, 'BAIANOPOLIS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290260, 'BAIXA GRANDE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290265, 'BANZAE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290270, 'BARRA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290280, 'BARRA DA ESTIVA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290290, 'BARRA DO CHOCA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290300, 'BARRA DO MENDES', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290310, 'BARRA DO ROCHA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290320, 'BARREIRAS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290323, 'BARRO ALTO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290327, 'BARROCAS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290330, 'BARRO PRETO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290340, 'BELMONTE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290350, 'BELO CAMPO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290360, 'BIRITINGA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290370, 'BOA NOVA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290380, 'BOA VISTA DO TUPIM', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290390, 'BOM JESUS DA LAPA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290395, 'BOM JESUS DA SERRA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290400, 'BONINAL', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290405, 'BONITO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290410, 'BOQUIRA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290420, 'BOTUPORA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290430, 'BREJOES', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290440, 'BREJOLANDIA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290450, 'BROTAS DE MACAUBAS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290460, 'BRUMADO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290470, 'BUERAREMA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290475, 'BURITIRAMA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290480, 'CAATIBA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290485, 'CABACEIRAS DO PARAGUACU', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290490, 'CACHOEIRA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290500, 'CACULE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290510, 'CAEM', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290515, 'CAETANOS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290520, 'CAETITE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290530, 'CAFARNAUM', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290540, 'CAIRU', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290550, 'CALDEIRAO GRANDE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290560, 'CAMACAN', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290570, 'CAMACARI', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290580, 'CAMAMU', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290590, 'CAMPO ALEGRE DE LOURDES', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290600, 'CAMPO FORMOSO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290610, 'CANAPOLIS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290620, 'CANARANA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290630, 'CANAVIEIRAS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290640, 'CANDEAL', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290650, 'CANDEIAS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290660, 'CANDIBA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290670, 'CANDIDO SALES', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290680, 'CANSANCAO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290682, 'CANUDOS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290685, 'CAPELA DO ALTO ALEGRE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290687, 'CAPIM GROSSO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290689, 'CARAIBAS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290690, 'CARAVELAS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290700, 'CARDEAL DA SILVA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290710, 'CARINHANHA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290720, 'CASA NOVA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290730, 'CASTRO ALVES', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290740, 'CATOLANDIA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290750, 'CATU', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290755, 'CATURAMA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290760, 'CENTRAL', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290770, 'CHORROCHO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290780, 'CICERO DANTAS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290790, 'CIPO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290800, 'COARACI', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290810, 'COCOS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290820, 'CONCEICAO DA FEIRA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290830, 'CONCEICAO DO ALMEIDA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290840, 'CONCEICAO DO COITE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290850, 'CONCEICAO DO JACUIPE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290860, 'CONDE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290870, 'CONDEUBA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290880, 'CONTENDAS DO SINCORA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290890, 'CORACAO DE MARIA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290900, 'CORDEIROS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290910, 'CORIBE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290920, 'CORONEL JOAO SA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290930, 'CORRENTINA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290940, 'COTEGIPE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290950, 'CRAVOLANDIA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290960, 'CRISOPOLIS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290970, 'CRISTOPOLIS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290980, 'CRUZ DAS ALMAS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (290990, 'CURACA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291000, 'DARIO MEIRA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291005, 'DIAS D AVILA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291010, 'DOM BASILIO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291020, 'DOM MACEDO COSTA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291030, 'ELISIO MEDRADO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291040, 'ENCRUZILHADA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291050, 'ENTRE RIOS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291060, 'ESPLANADA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291070, 'EUCLIDES DA CUNHA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291072, 'EUNAPOLIS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291075, 'FATIMA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291077, 'FEIRA DA MATA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291080, 'FEIRA DE SANTANA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291085, 'FILADELFIA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291090, 'FIRMINO ALVES', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291100, 'FLORESTA AZUL', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291110, 'FORMOSA DO RIO PRETO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291120, 'GANDU', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291125, 'GAVIAO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291130, 'GENTIO DO OURO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291140, 'GLORIA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291150, 'GONGOGI', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291160, 'GOVERNADOR MANGABEIRA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291165, 'GUAJERU', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291170, 'GUANAMBI', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291180, 'GUARATINGA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291185, 'HELIOPOLIS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291190, 'IACU', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291200, 'IBIASSUCE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291210, 'IBICARAI', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291220, 'IBICOARA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291230, 'IBICUI', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291240, 'IBIPEBA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291250, 'IBIPITANGA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291260, 'IBIQUERA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291270, 'IBIRAPITANGA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291280, 'IBIRAPUA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291290, 'IBIRATAIA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291300, 'IBITIARA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291310, 'IBITITA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291320, 'IBOTIRAMA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291330, 'ICHU', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291340, 'IGAPORA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291345, 'IGRAPIUNA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291350, 'IGUAI', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291360, 'ILHEUS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291370, 'INHAMBUPE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291380, 'IPECAETA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291390, 'IPIAU', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291400, 'IPIRA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291410, 'IPUPIARA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291420, 'IRAJUBA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291430, 'IRAMAIA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291440, 'IRAQUARA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291450, 'IRARA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291460, 'IRECE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291465, 'ITABELA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291470, 'ITABERABA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291480, 'ITABUNA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291490, 'ITACARE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291500, 'ITAETE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291510, 'ITAGI', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291520, 'ITAGIBA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291530, 'ITAGIMIRIM', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291535, 'ITAGUACU DA BAHIA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291540, 'ITAJU DO COLONIA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291550, 'ITAJUIPE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291560, 'ITAMARAJU', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291570, 'ITAMARI', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291580, 'ITAMBE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291590, 'ITANAGRA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291600, 'ITANHEM', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291610, 'ITAPARICA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291620, 'ITAPE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291630, 'ITAPEBI', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291640, 'ITAPETINGA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291650, 'ITAPICURU', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291660, 'ITAPITANGA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291670, 'ITAQUARA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291680, 'ITARANTIM', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291685, 'ITATIM', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291690, 'ITIRUCU', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291700, 'ITIUBA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291710, 'ITORORO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291720, 'ITUACU', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291730, 'ITUBERA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291733, 'IUIU', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291735, 'JABORANDI', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291740, 'JACARACI', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291750, 'JACOBINA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291760, 'JAGUAQUARA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291770, 'JAGUARARI', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291780, 'JAGUARIPE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291790, 'JANDAIRA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291800, 'JEQUIE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291810, 'JEREMOABO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291820, 'JIQUIRICA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291830, 'JITAUNA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291835, 'JOAO DOURADO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291840, 'JUAZEIRO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291845, 'JUCURUCU', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291850, 'JUSSARA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291855, 'JUSSARI', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291860, 'JUSSIAPE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291870, 'LAFAIETE COUTINHO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291875, 'LAGOA REAL', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291880, 'LAJE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291890, 'LAJEDAO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291900, 'LAJEDINHO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291905, 'LAJEDO DO TABOCAL', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291910, 'LAMARAO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291915, 'LAPAO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291920, 'LAURO DE FREITAS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291930, 'LENCOIS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291940, 'LICINIO DE ALMEIDA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291950, 'LIVRAMENTO DE NOSSA SENHORA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291955, 'LUIS EDUARDO MAGALHAES', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291960, 'MACAJUBA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291970, 'MACARANI', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291980, 'MACAUBAS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291990, 'MACURURE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291992, 'MADRE DE DEUS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (291995, 'MAETINGA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292000, 'MAIQUINIQUE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292010, 'MAIRI', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292020, 'MALHADA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292030, 'MALHADA DE PEDRAS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292040, 'MANOEL VITORINO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292045, 'MANSIDAO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292050, 'MARACAS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292060, 'MARAGOGIPE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292070, 'MARAU', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292080, 'MARCIONILIO SOUZA', 'BA')v
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292090, 'MASCOTE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292100, 'MATA DE SAO JOAO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292105, 'MATINA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292110, 'MEDEIROS NETO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292120, 'MIGUEL CALMON', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292130, 'MILAGRES', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292140, 'MIRANGABA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292145, 'MIRANTE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292150, 'MONTE SANTO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292160, 'MORPARA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292170, 'MORRO DO CHAPEU', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292180, 'MORTUGABA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292190, 'MUCUGE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292200, 'MUCURI', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292205, 'MULUNGU DO MORRO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292210, 'MUNDO NOVO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292220, 'MUNIZ FERREIRA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292225, 'MUQUEM DE SAO FRANCISCO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292230, 'MURITIBA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292240, 'MUTUIPE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292250, 'NAZARE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292260, 'NILO PECANHA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292265, 'NORDESTINA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292270, 'NOVA CANAA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292273, 'NOVA FATIMA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292275, 'NOVA IBIA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292280, 'NOVA ITARANA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292285, 'NOVA REDENCAO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292290, 'NOVA SOURE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292300, 'NOVA VICOSA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292303, 'NOVO HORIZONTE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292305, 'NOVO TRIUNFO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292310, 'OLINDINA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292320, 'OLIVEIRA DOS BREJINHOS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292330, 'OURICANGAS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292335, 'OUROLANDIA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292340, 'PALMAS DE MONTE ALTO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292350, 'PALMEIRAS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292360, 'PARAMIRIM', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292370, 'PARATINGA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292380, 'PARIPIRANGA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292390, 'PAU BRASIL', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292400, 'PAULO AFONSO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292405, 'PE DE SERRA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292410, 'PEDRAO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292420, 'PEDRO ALEXANDRE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292430, 'PIATA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292440, 'PILAO ARCADO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292450, 'PINDAI', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292460, 'PINDOBACU', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292465, 'PINTADAS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292467, 'PIRAI DO NORTE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292470, 'PIRIPA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292480, 'PIRITIBA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292490, 'PLANALTINO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292500, 'PLANALTO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292510, 'POCOES', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292520, 'POJUCA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292525, 'PONTO NOVO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292530, 'PORTO SEGURO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292540, 'POTIRAGUA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292550, 'PRADO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292560, 'PRESIDENTE DUTRA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292570, 'PRESIDENTE JANIO QUADROS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292575, 'PRESIDENTE TANCREDO NEVES', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292580, 'QUEIMADAS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292590, 'QUIJINGUE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292593, 'QUIXABEIRA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292595, 'RAFAEL JAMBEIRO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292600, 'REMANSO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292610, 'RETIROLANDIA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292620, 'RIACHAO DAS NEVES', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292630, 'RIACHAO DO JACUIPE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292640, 'RIACHO DE SANTANA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292650, 'RIBEIRA DO AMPARO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292660, 'RIBEIRA DO POMBAL', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292665, 'RIBEIRAO DO LARGO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292670, 'RIO DE CONTAS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292680, 'RIO DO ANTONIO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292690, 'RIO DO PIRES', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292700, 'RIO REAL', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292710, 'RODELAS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292720, 'RUY BARBOSA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292730, 'SALINAS DA MARGARIDA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292740, 'SALVADOR', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292750, 'SANTA BARBARA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292760, 'SANTA BRIGIDA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292770, 'SANTA CRUZ CABRALIA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292780, 'SANTA CRUZ DA VITORIA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292790, 'SANTA INES', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292800, 'SANTALUZ', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292805, 'SANTA LUZIA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292810, 'SANTA MARIA DA VITORIA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292820, 'SANTANA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292830, 'SANTANOPOLIS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292840, 'SANTA RITA DE CASSIA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292850, 'SANTA TERESINHA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292860, 'SANTO AMARO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292870, 'SANTO ANTONIO DE JESUS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292880, 'SANTO ESTEVAO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292890, 'SAO DESIDERIO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292895, 'SAO DOMINGOS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292900, 'SAO FELIX', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292905, 'SAO FELIX DO CORIBE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292910, 'SAO FELIPE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292920, 'SAO FRANCISCO DO CONDE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292925, 'SAO GABRIEL', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292930, 'SAO GONCALO DOS CAMPOS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292935, 'SAO JOSE DA VITORIA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292937, 'SAO JOSE DO JACUIPE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292940, 'SAO MIGUEL DAS MATAS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292950, 'SAO SEBASTIAO DO PASSE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292960, 'SAPEACU', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292970, 'SATIRO DIAS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292975, 'SAUBARA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292980, 'SAUDE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (292990, 'SEABRA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293000, 'SEBASTIAO LARANJEIRAS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293010, 'SENHOR DO BONFIM', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293015, 'SERRA DO RAMALHO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293020, 'SENTO SE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293030, 'SERRA DOURADA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293040, 'SERRA PRETA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293050, 'SERRINHA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293060, 'SERROLANDIA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293070, 'SIMOES FILHO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293075, 'SITIO DO MATO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293076, 'SITIO DO QUINTO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293077, 'SOBRADINHO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293080, 'SOUTO SOARES', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293090, 'TABOCAS DO BREJO VELHO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293100, 'TANHACU', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293105, 'TANQUE NOVO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293110, 'TANQUINHO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293120, 'TAPEROA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293130, 'TAPIRAMUTA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293135, 'TEIXEIRA DE FREITAS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293140, 'TEODORO SAMPAIO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293150, 'TEOFILANDIA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293160, 'TEOLANDIA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293170, 'TERRA NOVA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293180, 'TREMEDAL', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293190, 'TUCANO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293200, 'UAUA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293210, 'UBAIRA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293220, 'UBAITABA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293230, 'UBATA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293240, 'UIBAI', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293245, 'UMBURANAS', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293250, 'UNA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293260, 'URANDI', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293270, 'URUCUCA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293280, 'UTINGA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293290, 'VALENCA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293300, 'VALENTE', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293305, 'VARZEA DA ROCA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293310, 'VARZEA DO POCO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293315, 'VARZEA NOVA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293317, 'VARZEDO', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293320, 'VERA CRUZ', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293325, 'VEREDA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293330, 'VITORIA DA CONQUISTA', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293340, 'WAGNER', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293345, 'WANDERLEY', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293350, 'WENCESLAU GUIMARAES', 'BA');
INSERT INTO CIDADE (ID_CIDADE, TX_DESCRICAO, ESTADO_ID) VALUES  (293360, 'XIQUE-XIQUE', 'BA');
